server:
  port: ${PORT:8081}                             #8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}         #jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username:  ${DB_USERNAME}               #root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # =========================
  # EMAIL CONFIGURATION
  # =========================
  mail:
    host: smtp.gmail.com
    port: 587

    # Your Gmail
    username: ${MAIL_USERNAME}                                   #learnify852@gmail.com

    # Google App Password (NOT normal Gmail password)
    password: ${MAIL_PASSWORD}                  #ihnkdcgducqphkev

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # =========================
  # GOOGLE OAUTH2
  # =========================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

            scope:
              - email
              - profile

            redirect-uri: https://learnify-api-gateway.onrender.com/login/oauth2/code/google          #http://localhost:8081/login/oauth2/code/google

# =========================
# EUREKA
# =========================
eureka:
  client:
    service-url:
      defaultZone: https://learnify-eureka.onrender.com/eureka            #defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

# =========================
# JWT
# =========================
jwt:
  secret: ${JWT_SECRET}               #learnify-super-secret-key-must-be-at-least-32-characters-long
  expiration-ms: 86400000